---
- name: Add docker APT key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
  become: True


- name: Add docker APT repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: True
  become: True


- name: Install docker-ce
  package:
    name: docker-ce
    state: latest
  become: True


- name: Install python-docker
  package:
    name: python-docker
    state: latest
  become: True
