---
- name: Include components
  include_tasks:
    file: "components/{{ component }}.yml"
  loop_control:
    loop_var: component
  loop:
    - volumes
    - container
    - datasources
    - folders
    - dashboards
