---
- hosts: nuc
  vars_files:
    - secrets.yml
  roles:
    - common
    - docker
#   - influxdb
#    - grafana


- hosts: cluster
  vars_files:
    - secrets.yml
  roles:
    - common
    - docker
