---
#nodes
- hosts: all
  vars_files:
    - secrets.yml
  roles:
    - common
    - fail2ban
    - docker
    - telegraf


- hosts: monitoring
  vars_files:
    - secrets.yml
  collections:
    - community.grafana
  roles:
    - influxdb
    - grafana


- hosts: dns
  vars_files:
    - secrets.yml
  roles:
    - pihole


#- hosts: vpn
#  vars_files:
#    - secrets.yml
#  roles:
#    - openvpn


- hosts: git
  vars_files:
    - secrets.yml
  roles:
    - gitlab


- hosts: password_manager
  vars_files:
    - secrets.yml
  roles:
    - bitwarden


- hosts: minecraft
  vars_files:
    - secrets.yml
  roles:
    - minecraft_server
