---
- hosts: nuc
  vars_files:
    - secrets.yml
  roles:
    - common
    - docker
    - influxdb
    - telegraf
    - grafana
    - jaeger
    - jenkins


- hosts: cluster
  vars_files:
    - secrets.yml
  roles:
    - common
    - docker
    - telegraf


#- hosts: minecraft
#  vars_files:
#    - secrets.yml
#  roles:
#    - common
#    - docker
#    - minecraft_server
