---
- name: "Wait until influxdb is available on port {{ influxdb.port }}"
  wait_for:
    port: "{{ influxdb.port }}"


- name: Create read user and grant access
  influxdb_user:
    hostname: "{{ influxdb.hostname }}"
    port: "{{ influxdb.port }}"

    # This is necessary due to a bug in the Ansible influxdb module
    udp_port: 4444

    username: "{{ influxdb.admin.username }}"
    password: "{{ influxdb.admin.password }}"

    user_name: "{{ influxdb.read.username }}"
    user_password: "{{ influxdb.read.password }}"

# Not supported until Ansible 2.8
#    grants:
#      - database: "{{ influxdb.database }}"
#        privilege: READ



- name: Create write user and grant access
  influxdb_user:
    hostname: "{{ influxdb.hostname }}"
    port: "{{ influxdb.port }}"

    # This is necessary due to a bug in the Ansible influxdb module
    udp_port: 4444
    
    username: "{{ influxdb.admin.username }}"
    password: "{{ influxdb.admin.password }}"

    user_name: "{{ influxdb.write.username }}"
    user_password: "{{ influxdb.write.password }}"

#    grants:
#      - database: "{{ influxdb.database }}"
#        privilege: WRITE
