---
- name: Create openvpn docker container
  docker_container:
    name: openvpn
    image: linuxserver/openvpn-as:latest
    state: started
    ports:
      - "{{ openvpn.web.https.port }}:943/tcp"
      - "{{ openvpn.udp.port }}:1194/udp"
    env:
      TZ: "{{ openvpn.timezone }}"
    capabilities:
      - NET_ADMIN
    volumes:
      - openvpn:/config
  become: True
