---
- name: Include components
  include_tasks:
    file: "components/{{ component }}.yml"
  loop_control:
    loop_var: component
  loop:
    - hostname
    - apt
    - users
    - sudo
    - openssh_server
    - ntp
    - python
    - ca_certificates
